/* EFFACEMENT DE LA BASE DE DONNÉES */
DROP DATABASE IF EXISTS news;

/* CREATION DE LA BASE DE DONNÉES */
CREATE DATABASE news DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

/* SÉLÉCTION DE LA BASE DE DONNÉES */
USE news;

/* CRÉATION DE LA TABLE NEWS */
CREATE TABLE IF NOT EXISTS news
(
    id SMALLINT(6) UNSIGNED AUTO_INCREMENT,
    auteur VARCHAR(25) NOT NULL,
    titre VARCHAR(100) NOT NULL,
    contenu TEXT NOT NULL,
    dateAjout datetime NOT NULL,
    dateModif datetime NOT NULL,
    CONSTRAINT pk_news PRIMARY KEY(id),
    CONSTRAINT titre_unique UNIQUE(titre)
) DEFAULT CHARSET=utf8 ;

/* CRÉATION DE LA TABLE COMMENTS */
CREATE TABLE IF NOT EXISTS comments (
  id SMALLINT(6) UNSIGNED AUTO_INCREMENT,
  news SMALLINT(6) UNSIGNED NOT NULL,
  auteur VARCHAR(50) NOT NULL,
  contenu TEXT NOT NULL,
  date datetime NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (id),
  CONSTRAINT fk_com_news FOREIGN KEY(news) REFERENCES news(id)
  ON UPDATE CASCADE ON DELETE CASCADE
) DEFAULT CHARSET=utf8 ;